---
title: "Final Project"
due date: "12/14/2021"
author: "Gus Vu & Jeremy Bednar"
output: html_notebook
---

### Load Libraries & Data

```{r include=FALSE}
library(jsonlite)
library(lubridate)
library(gghighlight)
library(spotifyr)
library(tidyverse)
library(knitr)
library(ggplot2)
library(plotly)
library(esquisse)
library(dplyr)
library(purrr)
library(ggridges)
library(reticulate)

# Gus history
streamHistoryGus0 <- fromJSON("GusStreamingHistory0.json", flatten = TRUE)
streamHistoryGus1 <- fromJSON("GusStreamingHistory1.json", flatten = TRUE)

# Jeremy history
streamHistoryJeremy0 <- fromJSON("JeremyStreamingHistory0 copy.json", flatten = TRUE)
streamHistoryJeremy1 <- fromJSON("JeremyStreamingHistory1 copy.json", flatten = TRUE)
streamHistoryJeremy2 <- fromJSON("JeremyStreamingHistory2 copy.json", flatten = TRUE)
streamHistoryJeremy3 <- fromJSON("JeremyStreamingHistory3 copy.json", flatten = TRUE)
streamHistoryJeremy4 <- fromJSON("JeremyStreamingHistory4 copy.json", flatten = TRUE)

# Joining Data Frames Per User + converting "msPlayed" to seconds
streamHistoryJeremy <-
  streamHistoryJeremy0 %>%
  full_join(streamHistoryJeremy1) %>%
  full_join(streamHistoryJeremy2) %>%
  full_join(streamHistoryJeremy3) %>%
  full_join(streamHistoryJeremy4) %>%
  mutate(Listener = "Jeremy") %>%
  mutate(sPlayed = msPlayed/1000)

streamHistoryGus <-
  streamHistoryGus0 %>%
  full_join(streamHistoryGus1) %>%
  mutate(Listener = "Gus") %>%
  mutate(sPlayed = msPlayed/1000)

#API Access (Gus)
Sys.setenv(SPOTIFY_CLIENT_ID = '949891eb08fe47cb8e6e031a841b76ba')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '54b9813cd7bc40eca15514be0b52701b')

access_token <- get_spotify_access_token()
```

### Total Listening Length Per User (in seconds)

```{r}
#Total listening time of the time interval for which the data was collected (including "banned artists")
streamHistoryTotalJeremy <- 
  streamHistoryJeremy %>%
  summarise(TotalPlayed = sum(sPlayed))
streamHistoryTotalJeremy

streamHistoryTotalGus <- 
  streamHistoryGus %>%
  summarise(TotalPlayed = sum(sPlayed))
streamHistoryTotalGus

```

### Listening Length Per User By Song

```{r}
#total listening time per song
streamHistoryJeremySong <- 
    streamHistoryJeremy %>%
    group_by(trackName, artistName) %>%
    select(artistName, trackName, sPlayed) %>%
    summarize(sTotal = sum(sPlayed)) %>%
    mutate(Listener = "Jeremy")

streamHistoryGusSong <- 
    streamHistoryGus %>%
    group_by(trackName, artistName) %>%
    select(artistName, trackName, sPlayed) %>%
    summarize(sTotal = sum(sPlayed)) %>%
    mutate(Listener = "Gus")

```

### Listening Length Per User By Artist

```{r}
#total listening time for all artists
streamHistoryJeremyArtist <- 
    streamHistoryJeremy %>%
    group_by(artistName) %>%
    select(artistName, trackName, sPlayed) %>%
    summarize(sTotal = sum(sPlayed)) %>%
    mutate(Listener = "Jeremy")

streamHistoryGusArtist <- 
    streamHistoryGus %>%
    group_by(artistName) %>%
    select(artistName, trackName, sPlayed) %>%
    summarize(sTotal = sum(sPlayed)) %>%
    mutate(Listener = "Gus")

```

### Gus and Jeremy Full Join (streamHistory, Song, and Artist)

```{r}
#combining the original streamHistory tables for Gus & Jeremy
streamHistoryGusAndJeremyOG <-
  streamHistoryGus %>%
  full_join(streamHistoryJeremy) 

#total listening time per song for both users
streamHistoryGusAndJeremySong<-
  streamHistoryGusSong %>%
  full_join(streamHistoryJeremySong) %>%
  filter(trackName != "Unknown Track") %>%
  arrange(desc(sTotal))

#total listening time for all artists either user listened to
streamHistoryGusAndJeremyArtist <-
  streamHistoryGusArtist %>%
  full_join(streamHistoryJeremyArtist) %>%
  arrange(desc(sTotal))

streamHistoryGusAndJeremySong %>%
  head(10)


```

### Top 10 Songs

```{r}

#Top 10 songs Gus
GusTopTenSong <-
  streamHistoryGusSong %>%
  filter(trackName != "Unknown Track") %>%
  arrange(desc(sTotal)) %>%
  head(10)
ggplot(GusTopTenSong) +
  aes(x = reorder(trackName,+sTotal), fill = artistName, weight = sTotal) +
  geom_bar() +
  scale_fill_hue(direction = 1) +
  labs(title = "Gus Top 10 Songs") +
  coord_flip() +
  theme_bw() +
  xlab("Track Name") +
  ylab("Total Listened (Seconds)")

#Top 10 Songs Jeremy
JeremyTopTenSong <-
  streamHistoryJeremySong %>%
  filter(trackName != "Unknown Track") %>%
  arrange(desc(sTotal)) %>%
  head(10)
ggplot(JeremyTopTenSong) +
  aes(x = reorder(trackName,+sTotal), fill = artistName, weight = sTotal) +
  geom_bar() +
  scale_fill_hue(direction = 1) +
  labs(title = "Jeremy Top 10 Songs") +
  coord_flip() +
  theme_bw() +
  xlab("Track Name") +
  ylab("Total Listened (Seconds)")
```

### Top 10 Artists
```{r}
#graphs and visuals for significant information
GusTopTenArtist <-
  streamHistoryGusArtist %>%
  filter(artistName != "Unknown Artist") %>%
  arrange(desc(sTotal)) %>%
  head(10)
ggplot(GusTopTenArtist) +
  aes(x = reorder(artistName,+sTotal), fill = artistName, weight = sTotal) +
  geom_bar() +
  scale_fill_hue(direction = 1) +
  labs(title = "Top 10 Artists For Gus") +
  coord_flip() +
  theme_bw() +
  xlab("Artist") +
  ylab("Total Listened (Seconds)")

JeremyTopTenArtist <-
  streamHistoryJeremyArtist %>%
  filter(artistName != "Unknown Artist") %>%
  arrange(desc(sTotal)) %>%
  head(10)
ggplot(JeremyTopTenArtist) +
  aes(x = reorder(artistName,+sTotal), fill = artistName, weight = sTotal) +
  geom_bar() +
  scale_fill_hue(direction = 1) +
  labs(title = "Top 10 Artists For Jeremy") +
  coord_flip() +
  theme_bw() +
  xlab("Artist") +
  ylab("Total Listened (Seconds)")

```

### Initial CoPlaylist

```{r}
#creating a playlist of songs that both users listen to
CoPlaylist <-
  streamHistoryJeremySong %>%
  filter(sTotal <= 600000) %>%
  inner_join(streamHistoryGusSong, by = c("trackName" = "trackName","artistName" = "artistName")) 
CoPlaylist
```

### Top 10 Songs On CoPlaylist

```{r}
#songs each of us listen to a lot that the other has heard before
GusCoPlay <-
  CoPlaylist %>%
  select(trackName,artistName,sTotal.y,Listener.y) %>%
  arrange(desc(sTotal.y)) %>%
  head(15)
ggplot(GusCoPlay) +
  aes(x = reorder(trackName,+sTotal.y), fill = artistName, weight = sTotal.y) +
  geom_bar() +
  scale_fill_hue(direction = 1) +
  labs(title = "Gus' Top 15 Songs On CoPlayList") +
  ylab("Total Time (Seconds)") +
  xlab("Song Name") +
  coord_flip() +
  theme_bw()


JeremyCoPlay <-
  CoPlaylist %>%
  select(trackName,artistName,sTotal.x,Listener.x) %>%
  arrange(desc(sTotal.x)) %>%
  head(15)
ggplot(JeremyCoPlay) +
  aes(x = reorder(trackName,+sTotal.x), fill = artistName, weight = sTotal.x) +
  geom_bar() +
  scale_fill_hue(direction = 1) +
  labs(title = "Jeremy's Top 15 Songs On CoPlayList") +
  ylab("Total Time (Seconds)") +
  xlab("Song Name") +
  coord_flip() +
  theme_bw()

```

### Top 10 songs Audio Features

```{r}
GusAudioFeatures <-
  get_track_audio_features("2VjXGuPVVxyhMgER3Uz2Fe,0uEp9E98JB5awlA084uaIg,2tQM1BUrXp2kqOM6mN11TC,0Uyh92tLyb9JawG8lmWCzJ,2IyL2CyHoenwQLds5jSuqK,2IGmmvcqp9h3LcxG8SCT0U,7x6hO9VMAee9x1iWaeNkL6,3QLjDkgLh9AOEHlhQtDuhs,0bHs3ly4Bv5BlzE3KrePfX,6sIMSl1n3KDPr03Fw8mujd", authorization = access_token)

```


#Audio Features
```{r eval=FALSE, include=FALSE}
GusfavArtist1 <- get_artist_audio_features(artist= "Ms. Lauryn Hill")
GusfavArtist2 <- get_artist_audio_features(artist= "Erykah Badu")
GusfavArtist3 <- get_artist_audio_features(artist= "2Pac")
GusfavArtist4 <- get_artist_audio_features(artist= "Lil Wayne")
GusfavArtist5 <- get_artist_audio_features(artist= "Jay-Z")


GusTop5Audio <-
  GusfavArtist1 %>%
  full_join(GusfavArtist2)%>%
  full_join(GusfavArtist3)%>%
  full_join(GusfavArtist4)%>%
  full_join(GusfavArtist5)%>%
  summarise(danceability = sum(danceability)/5,energy = sum(energy)/5, tempo = sum(tempo)/5,speechiness = sum(speechiness)/5,acousticness = sum(acousticness)/5,instrumentalness = sum(instrumentalness)/5) 

#Make new data frame so we can graph easier
Audio_Features <- c("danceability", "energy", "tempo", "speechiness", "acousticness", "instrumentalness")
Score <- c(402.590400, 408.287008, 66377.763800, 158.053660, 91.696080, 6.327396)
Gus_Top_5Audio <- data.frame(Audio_Features, Score) 


ggplot(data = Gus_Top_5Audio, aes(x =Audio_Features, y = Score, fill = Audio_Features)) +
  geom_col() +
  labs(title = "Average Audio Features of Gus' Top 5 Artists")

JeremyfavArtist1 <- get_artist_audio_features(artist= "Lil Uzi Vert")
JeremyfavArtist2 <- get_artist_audio_features(artist= "Tyler, The Creator")
JeremyfavArtist3 <- get_artist_audio_features(artist= "Future")
JeremyfavArtist4 <- get_artist_audio_features(artist= "Juice WRLD")
JeremyfavArtist5 <- get_artist_audio_features(artist= "Playboi Carti")


JeremyTop5Audio <-
  JeremyfavArtist1 %>%
  full_join(JeremyfavArtist2)%>%
  full_join(JeremyfavArtist3)%>%
  full_join(JeremyfavArtist4)%>%
  full_join(JeremyfavArtist5)%>%
  summarise(danceability = sum(danceability)/5,energy = sum(energy)/5, tempo = sum(tempo)/5,speechiness = sum(speechiness)/5,acousticness = sum(acousticness)/5,instrumentalness = sum(instrumentalness)/5)


#Make new data frame so we can graph easier
JAudio_Features <- c("danceability", "energy", "tempo", "speechiness", "acousticness", "instrumentalness")
JScore <- c(208.6264, 178.6905, 38284.76, 65.90458, 51.64297, 6.977631)
Jeremy_Top_5Audio <- data.frame(JAudio_Features, JScore)

ggplot(data = Jeremy_Top_5Audio, aes(x =JAudio_Features, y = JScore, fill = Audio_Features)) +
  geom_col() +
  labs(title = "Average Audio Features of Jeremy's Top 5 Artists")+
  xlab("Audio_Features") +
  ylab("Score")

```
